src/Entity/Client.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @ApiResource(
 *     normalizationContext={"list"}
 * )
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="client")
     */
    private $commandes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telephone;

    /**
     * Client constructor.
     */
    public function __construct() {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getCommandes(): ArrayCollection
    {
        return $this->commandes;
    }

    /**
     * @param ArrayCollection $commandes
     */
    public function setCommandes(ArrayCollection $commandes): void
    {
        $this->commandes = $commandes;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 * @ApiResource(
 *     normalizationContext={"list"},
 *     collectionOperations={
 *         "post"={"method"="POST", "access_control"="is_granted('ROLE_USER')"}
 *     },
 *     itemOperations={
 *          "get" = { "security" = "is_granted('ROLE_USER')" },
 *          "put" = { "security" = "is_granted('ROLE_ADMIN')" },
 *          "delete" = { "security" = "is_granted('ROLE_ADMIN')" }
 *     },
 * )
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=false, options={"default" = 0})
     */
    private $prix_total;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CommandeStatut", inversedBy="commandes")
     */
    private $etat;

    /**
     * @ORM\OneToOne(targetEntity="Creneau", inversedBy="commande")
     * @ORM\JoinColumn(name="id_creneau", referencedColumnName="id_creneau")
     */
    private $creneau;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="commande", cascade={"remove"})
     */
    private $commande_lignes;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="commandes")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Magasin", inversedBy="commandes")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $magasin;

    /**
     * Commande constructor.
     */
    public function __construct() {
        $this->commande_lignes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getPrixTotal()
    {
        return $this->prix_total;
    }

    /**
     * @param mixed $prix_total
     */
    public function setPrixTotal($prix_total): void
    {
        $this->prix_total = $prix_total;
    }

    /**
     * @return CommandeStatut
     */
    public function getEtat(): ?CommandeStatut
    {
        return $this->etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat): void
    {
        $this->etat = $etat;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getCommandeLignes()
    {
        return $this->commande_lignes;
    }

    /**
     * @param ArrayCollection $commande_lignes
     */
    public function setCommandeLignes(ArrayCollection $commande_lignes): void
    {
        $this->commande_lignes = $commande_lignes;
    }

    /**
     * @return mixed
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * @param mixed $client
     */
    public function setClient($client): void
    {
        $this->client = $client;
    }

    /**
     * @return mixed
     */
    public function getMagasin()
    {
        return $this->magasin;
    }

    /**
     * @param mixed $magasin
     */
    public function setMagasin($magasin): void
    {
        $this->magasin = $magasin;
    }

    /**
     * @return mixed
     */
    public function getCreneau()
    {
        return $this->creneau;
    }

    /**
     * @param mixed $creneau
     */
    public function setCreneau($creneau): void
    {
        $this->creneau = $creneau;
    }

}

src/Entity/LigneCommande.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\LigneCommandeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigneCommandeRepository::class)
 * @ApiResource(
 *     normalizationContext={"list"},
 *     collectionOperations={
 *         "post"={"method"="POST", "access_control"="is_granted('ROLE_ADMIN')"}
 *     },
 *     itemOperations={
 *          "get" = { "security" = "is_granted('ROLE_USER')" },
 *          "put" = { "security" = "is_granted('ROLE_ADMIN')" },
 *          "delete" = { "security" = "is_granted('ROLE_ADMIN')" }
 *     },
 * )
 */
class LigneCommande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Commande", inversedBy="commande_lignes")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $commande;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="command_lignes")
     */
    private $produit;

    /**
     * @ORM\Column(type="float", nullable=false, options={"default" = 0})
     */
    private $prix_tot;

    /**
     * LigneCommande constructor.
     */
    public function __construct() {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param mixed $quantity
     */
    public function setQuantity($quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * @return mixed
     */
    public function getCommande()
    {
        return $this->commande;
    }

    /**
     * @param mixed $commande
     */
    public function setCommande($commande): void
    {
        $this->commande = $commande;
    }

    /**
     * @return mixed
     */
    public function getProduit()
    {
        return $this->produit;
    }

    /**
     * @param mixed $produit
     */
    public function setProduit($produit): void
    {
        $this->produit = $produit;
    }

    /**
     * @return mixed
     */
    public function getPrixTot()
    {
        return $this->prix_tot;
    }

    /**
     * @param mixed $prix_tot
     */
    public function setPrixTot($prix_tot): void
    {
        $this->prix_tot = $prix_tot;
    }

}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use App\Entity\CommandeStatut;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('etat', EntityType::class, [
                'label' => 'Etat',
                'attr' => ['class' => 'form-control'],
                'class'  => CommandeStatut::class,
                'choice_label' => 'label',
                'expanded' => false,
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

templates/commande/commande-creneau.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="container text-center">
        <h2 class="mb-5">Choisir un créneau pour récupérer votre commande</h2>
        {{ form_start(formCreneau) }}
            {{ form_label(formCreneau.creneaux) }}
            {{ form_widget(formCreneau.creneaux) }}
            <button type="submit" class="btn btn-primary mt-5">Valider</button>
        {{ form_end(formCreneau) }}
    </div>


{% endblock %}

templates/commande/commande-prete-email.html.twig
{% extends "email/layout.html.twig" %}

{% set total = 0 %}

{% block content %}
    <table width="100%" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td data-color="title" data-size="size title" data-min="20" data-max="40" data-link-color="link title color" data-link-style="text-decoration:none; color:#292c34;" class="title" align="center" style="font:30px/33px Arial, Helvetica, sans-serif; color:#292c34; padding:0 0 23px;">
                Votre commande est prête choisir votre créneau de réception
            </td>
        </tr>
        <tr>
            <td data-color="text" data-size="size text" data-min="10" data-max="26" data-link-color="link text color" data-link-style="font-weight:bold; text-decoration:underline; color:#40aceb;" align="center" style="font:16px/29px Arial, Helvetica, sans-serif; color:#888; padding:0 0 21px;">

            </td>
        </tr>
        <tr>
            <td style="padding: 0 0 20px;">
                <table width="134" align="center" style="margin:0 auto;" cellpadding="0"  cellspacing="0">
                    <tbody>
                    <tr>
                        <td data-bgcolor="bg-button" data-size="size button" data-min="10" data-max="16" class="btn" align="center" style="font:12px/14px Arial, Helvetica, sans-serif; color:#f8f9fb; text-transform:uppercase; mso-padding-alt:12px 10px 10px; border-radius:2px;" bgcolor="#7bb84f">
                            <a target="_blank" href="{{ url('commande_list') }}" style="text-decoration:none; color:#f8f9fb; display:block; padding:12px 10px 10px;">
                                Voir mes commande
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/commande/confirmation-email.html.twig
{% extends "email/layout.html.twig" %}

{% set total = 0 %}

{% block content %}
    <table width="100%" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
            <td data-color="title" data-size="size title" data-min="20" data-max="40" data-link-color="link title color" data-link-style="text-decoration:none; color:#292c34;" class="title" align="center" style="font:30px/33px Arial, Helvetica, sans-serif; color:#292c34; padding:0 0 23px;">
                Confirmation de votre commande
            </td>
        </tr>
        <tr>
            <td data-color="text" data-size="size text" data-min="10" data-max="26" data-link-color="link text color" data-link-style="font-weight:bold; text-decoration:underline; color:#40aceb;" align="center" style="font:16px/29px Arial, Helvetica, sans-serif; color:#888; padding:0 0 21px;">
                {% if commandes|length > 1 %}
                    Vos commandes N°
                    {% for commande in commandes %}
                        {{ commande.id ~ ', ' }}
                        {% set total = total + commande.prixTotal %}
                    {% endfor %}
                    ont bien été enregistré par nos services.
                {% else %}
                    {% set total = commandes[0].prixTotal %}
                    Votre commande N° {{ commandes[0].id }} a bien été enregistré par nos services.
                {% endif %}
                Pour un prix global de <strong>{{ total }} €</strong>
            </td>
        </tr>
        <tr>
            <td style="padding: 0 0 20px;">
                <table width="134" align="center" style="margin:0 auto;" cellpadding="0"  cellspacing="0">
                    <tbody>
                    <tr>
                        <td data-bgcolor="bg-button" data-size="size button" data-min="10" data-max="16" class="btn" align="center" style="font:12px/14px Arial, Helvetica, sans-serif; color:#f8f9fb; text-transform:uppercase; mso-padding-alt:12px 10px 10px; border-radius:2px;" bgcolor="#7bb84f">
                            <a target="_blank" href="{{ url('magasin_list') }}" style="text-decoration:none; color:#f8f9fb; display:block; padding:12px 10px 10px;">
                                Visiter le site
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/commande/detail.html.twig
{% extends 'base.html.twig' %}

{% set total = 0 %}

{% block body %}

    <div class="row">
        <div class="col-md-8">
            <div class="card shadow-sm mt-3">
                <div class="card-body">
                    <h3 class="card-title mb-5">Récapitulatif de {{ commandes|length > 1 ? 'Mes Commandes' : 'Ma Commande' }}</h3>
                    {% for commande in commandes %}
                        <div class="card shadow-sm mt-3 mb-4">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h4 class="card-title">Votre commande N° {{ commande.id }}</h4>
                                    </div>
                                    <div class="col">
                                        <div class="text-right">
                                            <a href="{{ path('commande_cancel', {id: commande.id}) }}" class="text-danger" role="button">Annuler la commande</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="text-right">
                                    <small class="card-title text-right">Commande pour le magasin <strong>{{ commande.magasin.nom }}</strong></small>
                                </div>

                                <p class="card-text">Facturation :<br>
                                    <span style="font-size: 14px; margin-left: 20px;">{{ client.nom ~ ' ' ~ client.prenom }}</span><br>
                                    <span style="font-size: 14px; margin-left: 20px;">{{ client.adresse }}</span><br>
                                    <span style="font-size: 14px; margin-left: 20px;">{{ client.codePostal ~ ' - ' ~ client.ville }}</span>
                                </p>
                                <hr>
                                <p class="card-text font-weight-bold">Détail commande :</p>
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th scope="col">Produit</th>
                                        <th scope="col" class="text-center">Prix unitaire</th>
                                        <th scope="col" class="text-center">Quantité</th>
                                        <th scope="col" class="text-right">Prix Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for ligne in commande.commandeLignes %}
                                        <tr>
                                            <th scope="row">{{ ligne.produit.label }}</th>
                                            <td class="text-center">{{ ligne.produit.prix }} €</td>
                                            <td class="text-center">{{ ligne.quantity }}</td>
                                            <td class="text-right">{{ ligne.prixTot }} €</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                                <hr class="mt-5">
                                <div class="text-right">
                                    <p class="card-text font-weight-bold">Prix total de la commande : {{ commande.prixTotal }} €</p>
                                </div>
                            </div>
                        </div>

                        {% set total = total + commande.prixTotal %}
                    {% else %}
                        <h3 class="card-text text-center">Aucune commande en attente de payement</h3>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card shadow-sm mt-3">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Total de {{ commandes|length > 1 ? 'mes commandes' : 'ma commande'}}</h5>
                    <p class="card-text font-weight-bold text-right">{{ total }} €</p>

                    <div class="text-center">
                        <a href="{{ path('commande_paye') }}" class="btn btn-success mt-5" role="button">Commander et Payer</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>

{% endblock %}

templates/commande/gerer-commande-list.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2>Gérer les commandes :</h2>
    {% for commande in commandes %}

        {% if commande.etat.id == 1 %}
            {% set color = 'text-warning' %}
        {% elseif commande.etat.id == 2 %}
            {% set color = 'text-warning' %}
        {% elseif commande.etat.id == 3 %}
            {% set color = 'text-info' %}
        {% elseif commande.etat.id == 4 %}
            {% set color = 'text-succes' %}
        {% elseif commande.etat.id == 5 %}
            {% set color = 'text-danger' %}
        {% elseif commande.etat.id == 6 %}
            {% set color = 'text-secondary' %}
        {% endif %}

        <div class="card mt-5">
            <div class="card-body">
                <div class="card-title">
                    <p>Commande numéro : {{ commande.id }}</p>
                </div>
                <hr>
                <div class="row text-center">
                    <div class="col">
                        <h5 class="">Magasin</h5>
                        <p>{{ commande.magasin.nom }}</p>
                    </div>
                    <div class="col">
                        <h5 class="">Prix</h5>
                        <p>{{ commande.prixTotal }}€</p>
                    </div>
                    <div class="col">
                        <h5 class="">Etat</h5>
                        <p class="{{ color }}">{{ commande.etat.label }}</p>
                    </div>
                    <div class="col">
                        <a href="{{ path('commande_gerer_etat', {id: commande.id}) }}"><button class="btn btn-primary">Changer etat</button></a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/commande/gerer-commande.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container text-center">
        <h2 class="mb-5">Modifier l'état de la commande</h2>
        {{ form_start(form) }}
        {{ form_label(form.etat) }}
        {{ form_widget(form.etat) }}
        <button type="submit" class="btn btn-primary mt-5">Valider</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% set total = 0 %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="card shadow-sm mt-3">
                <div class="card-body">
                    <h3 class="card-title mb-5">Mon panier</h3>
                    {% for magasin in magasins %}
                        <div class="card shadow-sm mt-3 mb-4">
                            <div class="card-body">
                                <h4 class="card-title">Commande pour le magasin <strong>{{ magasin.magasin.nom }}</strong></h4>
                                {% for produit in magasin.produits %}
                                    {% set prix_total_produit = produit.produit.prix * produit.quantity %}
                                    <div class="card mb-3">
                                        <div class="row no-gutters">
                                            <div class="col-md-2">
                                                <img src="{{ asset('../../image/'~ produit.produit.label ~'.jpg') }}" class="card-img img-fluid" alt="...">
                                            </div>
                                            <div class="col-md-9">
                                                <div class="card-body d-flex flex-column h-100">
                                                    <h5 class="card-title mb-1 font-weight-bold">{{ produit.produit.label }}</h5>

                                                    <p class="card-text">Prix unitaire : {{ produit.produit.prix }} €</p>
                                                    <p class="card-text">Quantité : {{ produit.quantity }}</p>
                                                    <p class="card-text">Prix Total : {{ prix_total_produit }} €</p>
                                                </div>
                                            </div>
                                            <div class="col-md-1 text-right">
                                                <a href="{{ path('commande_remove_product', {id: magasin.magasin.id, id_product: produit.produit.id}) }}" class="btn btn-outline-danger" role="button"><i class="far fa-trash-alt"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                    {% set total = total + prix_total_produit %}
                                {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <h3 class="card-text text-center">Votre panier est vide !</h3>
                    {% endfor %}
                </div>
            </div>
            <div class="card shadow-sm mt-3">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Total de ma commande <span class="text-right">{{ total }} €</span></h5>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-5">
        <div class="col-md-6 text-left">
            <a href="{{ path('magasin_list') }}" class="btn btn-primary mt-5" role="button">Continuer mes achats</a>
        </div>
        <div class="col-md-6 text-right">
            <a href="{{ path('commande_create') }}" class="btn btn-success mt-5 {{ magasins is empty ? 'disabled' : '' }}" role="button" aria-disabled="{{ magasins is empty }}">Passer commande</a>
        </div>
    </div>


{% endblock %}

templates/commande/listCommande.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2>Mes commandes en cours :</h2>
    {% for commandeEnCours in commandesEnCours %}
        <div class="card mt-5">
            <div class="card-body">
                <div class="card-title">
                    <h4>Commande numéro : {{ commandeEnCours.id }}</h4>
                </div>
                <hr>
                <div class="row text-center">
                    {% if commandeEnCours.etat.id == 1%}
                        <div class="col">
                            <h5 class="">Prix</h5>
                            <p>{{ commandeEnCours.prixTotal }}€</p>
                        </div>
                        <div class="col">
                            <h5>Horraire</h5>
                            <p>En attente</p>
                        </div>
                        <div class="col">
                            <button class="btn btn-warning" disabled>{{ commandeEnCours.etat.label }}</button>
                        </div>
                    {% elseif commandeEnCours.etat.id == 2%}
                        <div class="col">
                            <h5 class="">Prix</h5>
                            <p>{{ commandeEnCours.prixTotal }}€</p>
                        </div>
                        <div class="col">
                            <h5>Horraire</h5>
                            <p>En attente</p>
                        </div>
                        <div class="col">
                            <button class="btn btn-warning" disabled>{{ commandeEnCours.etat.label }}</button>
                        </div>
                    {% elseif commandeEnCours.etat.id == 3%}
                        <div class="col">
                            <h5 class="">Prix</h5>
                            <p>{{ commandeEnCours.prixTotal }}€</p>
                        </div>
                        <div class="col">
                            <h5>Horraire</h5>
                            {% if commandeEnCours.creneau is null %}
                                <p>Choisir créneau</p>
                            {% else %}
                                <p>{{ commandeEnCours.creneau.date|date }}</p>
                            {% endif %}
                        </div>
                        <div class="col">
                            <a href="{{ path('commande_creneau', {id: commandeEnCours.id}) }}"><button class="btn btn-primary">{{ commandeEnCours.etat.label }}</button></a>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    {% endfor %}

    <h2 class="mt-5">Mes commandes passées :</h2>
    {% for commandeTerminer in commandesTerminer %}
        <div class="card mt-5">
            <div class="card-body">
                <div class="card-title">
                    <p>Commande numéro : {{ commandeTerminer.id }}</p>
                </div>
                <hr>
                <div class="row text-center">
                    {% if commandeTerminer.etat.id ==  4%}
                        <div class="col">
                            <h5 class="">Prix</h5>
                            <p>{{ commandeTerminer.prixTotal }}€</p>
                        </div>
                        <div class="col">
                            <h5>Horraire</h5>
                            <p>{{ commandeTerminer.creneau }}</p>
                        </div>
                        <div class="col">
                            <button class="btn btn-success" disabled>{{ commandeTerminer.etat.label }}</button>
                        </div>
                    {% elseif commandeTerminer.etat.id == 5 %}
                        <div class="col">
                            <h5 class="">Prix</h5>
                            <p>{{ commandeTerminer.prixTotal }}€</p>
                        </div>
                        <div class="col">
                            <h5>Horraire</h5>
                            <p>{{ commandeTerminer.creneau }}</p>
                        </div>
                        <div class="col">
                            <button class="btn btn-danger" disabled>{{ commandeTerminer.etat.label }}</button>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}